@host = http://localhost:8080

###
GET {{host}}/ping HTTP/1.1
content-type: application/json

### get all files
GET {{host}}/get-file-list HTTP/1.1
content-type: application/json

###
POST {{host}}/upload HTTP/1.1
content-type: multipart/form-data; boundary=----WebKitFormBoundarynsh5ZWs5fFZk50ou

------WebKitFormBoundarynsh5ZWs5fFZk50ou
Content-Disposition: form-data; name="name"

dd
------WebKitFormBoundarynsh5ZWs5fFZk50ou
Content-Disposition: form-data; name="email"

xx@sap.com
------WebKitFormBoundarynsh5ZWs5fFZk50ou
Content-Disposition: form-data; name="file"; filename="upload.mp4"
Content-Type: video/mp4

< ./cmd/web/html/sample-5s.mp4

------WebKitFormBoundarynsh5ZWs5fFZk50ou--

###
POST {{host}}/login HTTP/1.1
content-type: application/json

{
    "username":"litingting",
    "password":"123"
}

###
GET {{host}}/send-mq HTTP/1.1
content-type: application/json


###
GET {{host}}/receive-mq HTTP/1.1
content-type: application/json


###
GET {{host}}/get-minio HTTP/1.1
content-type: application/json


###
GET {{host}}/test-product HTTP/1.1
content-type: application/json


### upload vedio
POST {{host}}/upload-video HTTP/1.1
content-type: multipart/form-data; boundary=----WebKitFormBoundarynsh5ZWs5fFZk50ou

------WebKitFormBoundarynsh5ZWs5fFZk50ou
Content-Disposition: form-data; name="file"; filename="sample-5s.mp4"
Content-Type: video/mp4

< ./cmd/web/html/sample-5s.mp4

------WebKitFormBoundarynsh5ZWs5fFZk50ou--


### upload dummpy file
# (test by tony)
POST {{host}}/upload-video HTTP/1.1
content-type: multipart/form-data; boundary=----WebKitFormBoundarynsh5ZWs5fFZk50ou

------WebKitFormBoundarynsh5ZWs5fFZk50ou
Content-Disposition: form-data; name="file"; filename="test.py"
Content-Type: text/plain

< ./sample.text

------WebKitFormBoundarynsh5ZWs5fFZk50ou--


// 测试增加 file 和 status
###
POST {{host}}/insert-file-status HTTP/1.1
content-type: application/json

{
    "file_id":0,
    "status":2
}

// 测试增加 file 和 status
###
POST {{host}}/update-file-status HTTP/1.1
content-type: application/json

{
    "file_id":0,
    "status":1
}


// 测试删除 file
@fileId = 6
###
DELETE {{host}}/file/{{fileId}} HTTP/1.1
content-type: application/json